import { useTranslations } from "next-intl"
import Schedule from "./components/schedule.component";

const biolerplate = (<div>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sodales lectus vitae dui tincidunt, id lacinia odio hendrerit. Fusce eu vehicula lorem, eget venenatis elit. Cras cursus tortor quis feugiat accumsan. In eu commodo neque. Nulla pulvinar tortor ultrices cursus varius. Etiam facilisis leo eget ultricies gravida. In vitae auctor ante. Cras nec ligula erat. Suspendisse tempor non massa ut laoreet. Quisque erat elit, tempus non nisi sed, tincidunt condimentum eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

  Sed tristique felis mi, eget aliquam lectus tempus nec. Fusce et elit sollicitudin, gravida mauris suscipit, aliquam nibh. Mauris nec tempor neque, ut vehicula diam. Curabitur vestibulum, sem ut ornare luctus, justo enim rutrum risus, ut gravida turpis magna sit amet elit. Cras rhoncus quis urna in condimentum. Donec at turpis elementum, mattis odio sed, euismod est. Suspendisse aliquam at libero sit amet condimentum. Mauris eget odio nulla. Praesent elementum urna et dui venenatis viverra. Nulla id erat orci.

  Donec at ligula commodo, volutpat dui id, vehicula orci. Aliquam eu ultricies diam. Integer malesuada in libero eget porttitor. Fusce tempor ante sed elementum vehicula. Aenean ante ipsum, efficitur at facilisis id, suscipit id purus. Fusce sit amet sapien nibh. Maecenas porta id nisl ac volutpat. Nunc sapien arcu, fermentum venenatis ex eu, vulputate fringilla purus. Aliquam at bibendum augue. Ut sed odio non massa mattis tristique vitae maximus odio.

  In pretium turpis vel dolor congue lacinia id at dui. Sed scelerisque metus in nulla imperdiet consequat. Quisque mollis, urna ut facilisis laoreet, felis lacus tincidunt justo, quis rutrum nisl ex id nisi. Duis vitae metus a ligula placerat consequat id sit amet elit. Fusce pellentesque bibendum magna elementum rhoncus. Aenean ornare blandit purus, nec mollis lacus scelerisque vel. Phasellus id tortor sit amet nunc venenatis condimentum et a est. Quisque ullamcorper elit vel velit rhoncus lobortis. Praesent urna mauris, eleifend in mattis ut, venenatis ac orci. Nunc sed felis tempor sem facilisis commodo at id mi. Suspendisse laoreet orci magna, in hendrerit tellus volutpat et.

  Integer luctus lacus tempus erat gravida, sed varius magna tincidunt. Nam urna dolor, hendrerit eu aliquet quis, lacinia sit amet libero. Etiam pulvinar semper porta. In sit amet purus nunc. Vivamus non urna sapien. Ut ornare vehicula purus, sed ornare dolor laoreet ut. Sed pellentesque dignissim ligula, ac vehicula urna mattis nec. Phasellus sed ligula eget ipsum ultrices lacinia in nec magna. Vivamus metus turpis, ornare ut erat nec, mattis cursus augue. Aenean a erat vel est elementum mattis et non felis. Donec scelerisque lorem at luctus sollicitudin.

  Donec tempor varius dui quis feugiat. Morbi in blandit magna, non aliquet mauris. Nunc leo lectus, viverra vel ultrices nec, accumsan sed nibh. Mauris purus eros, mollis sed purus nec, varius dignissim massa. Quisque lacinia efficitur odio eget tempus. Morbi ultrices quam sit amet ipsum viverra mollis. Curabitur in nunc pretium leo tristique rutrum quis vitae ante.

  In egestas sem sed enim semper suscipit nec sit amet nisl. Sed vitae mi velit. Fusce rhoncus condimentum eros eget dapibus. Ut aliquam sed quam sit amet euismod. Duis suscipit erat non tempus bibendum. Curabitur mollis convallis augue, in venenatis nunc molestie at. Proin placerat tellus ut purus vulputate, in rutrum leo varius. In molestie lacinia euismod. Aliquam lobortis accumsan dui, at lobortis ligula maximus a. Phasellus lacus eros, consectetur ut justo accumsan, tempus malesuada lorem. Fusce quis semper diam. Vivamus quis mollis velit, at dapibus mauris. Ut pretium mollis lacinia. Fusce ac urna sed purus bibendum aliquet a sit amet mauris.

  Suspendisse pretium facilisis ante vitae tincidunt. Ut rutrum libero id feugiat volutpat. Morbi quis accumsan mi. Aliquam purus erat, rutrum ac eros id, maximus vehicula purus. Fusce ut ultrices eros. Suspendisse non est vel lectus pellentesque dapibus. Aliquam erat volutpat. Phasellus a nunc id lorem feugiat fringilla. Ut pharetra mi at facilisis dignissim. Proin in elit efficitur, scelerisque purus et, mattis est.

  Nunc ac quam eu nulla scelerisque mollis tincidunt vitae quam. Curabitur placerat semper nisl, vel vulputate purus luctus a. Aenean posuere et purus vel elementum. Mauris congue tristique augue et tempor. Nunc nec eros vitae eros fermentum ullamcorper eu at mauris. Praesent gravida feugiat mattis. Sed porta convallis lacus, nec laoreet nibh tincidunt quis. Nam elementum eleifend scelerisque. Vestibulum tincidunt cursus consectetur. Proin non commodo est. In congue tincidunt aliquam. Vestibulum nec consequat ipsum. Phasellus non mauris id eros efficitur interdum at et sapien. Vivamus ac gravida felis, ut pharetra nisl.

  Nullam maximus ante eget dictum porttitor. Fusce dapibus nibh eget leo ullamcorper varius non id turpis. Vivamus tempus dolor erat, nec elementum nisl pulvinar nec. Aliquam augue ipsum, maximus ac fermentum quis, dictum quis nisl. Cras vitae mattis purus, rutrum efficitur mi. Fusce ut risus ac quam hendrerit viverra. Sed lobortis fermentum ante. Nulla porttitor risus efficitur consequat bibendum. Donec rutrum suscipit lorem. Sed efficitur tincidunt dignissim.

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla purus arcu, placerat tristique magna vitae, ullamcorper pharetra mi. In placerat tempus enim vitae ultrices. Morbi eget semper erat, quis accumsan orci. Aenean eleifend lectus leo, a facilisis turpis lacinia sed. Quisque finibus, nisi eget ultrices blandit, mi magna faucibus mauris, vitae dapibus tortor mi posuere massa. Maecenas in consectetur sapien, quis ultricies erat. Praesent fringilla lobortis diam a porttitor. Integer mattis bibendum magna, eget aliquet ex porta a. Aenean nec gravida lectus, at dapibus justo. Vivamus id ex libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam non purus sed turpis accumsan placerat eu sit amet felis. Curabitur porta, arcu et gravida congue, magna dolor semper dolor, vel iaculis nisi dolor a erat. Ut eu turpis condimentum, venenatis elit nec, finibus dolor.

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. In non augue vitae orci semper dapibus et eget orci. Fusce at posuere lacus, in condimentum erat. Pellentesque at nisl magna. Vivamus vulputate eget ipsum a ornare. Integer iaculis id risus et ultrices. Ut laoreet, quam id luctus pellentesque, lorem nibh fermentum dui, nec ultricies eros quam nec mi. In fringilla sodales sem, in molestie velit ultricies at. Aenean ullamcorper sollicitudin quam. Suspendisse ac consectetur tellus. Cras nec tincidunt risus, ut vestibulum sem. Integer malesuada massa a dapibus lobortis. In at nibh dolor. Donec volutpat massa ullamcorper lorem euismod tempor a a dolor. Integer posuere ultrices nisl in suscipit. Maecenas tincidunt libero vel pellentesque tempus.

  Nulla facilisi. Quisque sed dolor accumsan, tincidunt orci nec, lobortis metus. Aliquam nec nibh arcu. Vestibulum mattis velit et sem lobortis, a iaculis orci pharetra. Mauris at neque aliquam, vestibulum eros vitae, rhoncus urna. Suspendisse suscipit ex tempus ligula feugiat interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus convallis dolor sed maximus posuere. Pellentesque eget rhoncus mi, convallis consequat dolor. Quisque ac nisl eget orci vestibulum fringilla id a libero. Donec a tellus non sapien ultrices tristique vel ac magna.

  Vestibulum ultrices dui neque, eu scelerisque mi mollis sit amet. Phasellus convallis faucibus nisl, ut semper metus volutpat nec. Nam suscipit vestibulum quam. Maecenas fermentum tellus vel purus elementum porttitor. Sed erat diam, scelerisque rhoncus dolor id, finibus tempus leo. Donec aliquam velit velit, a vehicula dolor eleifend et. Donec vitae nibh rutrum lorem pretium feugiat a congue ex. Pellentesque porttitor risus sit amet arcu pulvinar pharetra. Pellentesque lacinia lorem velit, sed feugiat ante consectetur at. Phasellus ut ligula malesuada, blandit velit non, mattis elit. Duis ornare malesuada velit.

  Aliquam ac sagittis mauris, in molestie tellus. Donec nec libero ac dolor molestie euismod ut vitae purus. Nam eget metus quis neque bibendum eleifend sed ut nisl. Praesent non orci sem. Aenean placerat, lorem vel luctus finibus, quam diam dapibus arcu, quis commodo velit neque id leo. Fusce consectetur urna sed volutpat porttitor. Quisque non nisi commodo tortor malesuada placerat non ac augue. Vivamus varius sagittis odio sed volutpat. Vivamus eu quam vel nunc ornare commodo in vel diam. Nunc vehicula condimentum dui vel molestie. Maecenas ante sem, malesuada vel eros nec, tincidunt lacinia sem.

  Quisque at volutpat dolor. Donec congue odio et scelerisque tempor. Ut malesuada congue metus id efficitur. Mauris felis nibh, euismod id libero a, laoreet dictum mi. Nulla venenatis pharetra nisl vel sollicitudin. Sed eget ligula lectus. Mauris viverra est vitae arcu luctus, in ultrices quam semper.

  Praesent elementum pretium tellus, eu lacinia neque venenatis pulvinar. Suspendisse suscipit a enim id hendrerit. Duis ultricies augue libero, sed placerat leo condimentum a. Mauris blandit neque non pretium sagittis. Fusce venenatis orci placerat euismod vehicula. In tellus risus, vulputate sit amet justo non, congue ornare libero. Curabitur ac lobortis felis. Curabitur congue euismod lacus, sit amet bibendum dui condimentum nec. Fusce id rutrum ipsum. Proin eget quam eget libero pulvinar pharetra non ut enim. Morbi consectetur felis eget fermentum varius. Aliquam quis libero ut risus dictum pharetra sed ut eros. Pellentesque id rhoncus urna.

  Pellentesque vitae libero nunc. Integer commodo, metus id accumsan egestas, nibh neque hendrerit libero, eget tincidunt sem ante a sapien. Phasellus rhoncus est justo, quis hendrerit urna sodales ut. Suspendisse nec ligula malesuada sem venenatis faucibus. Cras magna turpis, tincidunt non porta ut, semper sit amet enim. Ut sagittis mauris a dignissim auctor. Nulla nec tristique eros. Vestibulum id semper sem. Proin vel dictum nunc. In tortor neque, lacinia a bibendum a, condimentum nec turpis. Maecenas porta, felis vel convallis imperdiet, nunc turpis accumsan urna, vitae facilisis risus velit eget nulla. Donec condimentum dui sit amet neque dictum, vitae mollis nisl cursus. Quisque feugiat erat in lacus euismod, a facilisis nibh ullamcorper. Aliquam erat volutpat.

  In eget pharetra ipsum, id porta felis. Ut vel tempor dolor, pulvinar lacinia purus. Aenean interdum risus vel massa auctor, id gravida est iaculis. Maecenas risus augue, facilisis sed sagittis quis, consectetur at sapien. Aliquam quis ipsum hendrerit, tristique odio ut, tristique lacus. Fusce a leo congue, iaculis velit sed, ultrices massa. Pellentesque et nisi blandit, eleifend massa eu, consequat dolor. Suspendisse potenti. Duis dictum tincidunt turpis, sed dapibus quam auctor sed. Curabitur sagittis ut quam vitae scelerisque. Etiam ipsum purus, pulvinar sit amet volutpat a, accumsan egestas sem. Donec id ipsum ligula.

  Aenean dignissim placerat velit eu blandit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse vitae purus at nisl pharetra luctus. Fusce cursus luctus nulla, sed euismod lorem consequat in. Duis rutrum ligula ante. Fusce in augue et libero porta convallis. Etiam diam quam, maximus ut libero id, pretium ultrices elit. Vestibulum malesuada ullamcorper dictum.

  Nullam nec laoreet ex. Donec venenatis ut arcu ac commodo. Mauris quis elit arcu. Maecenas ultrices, lorem quis accumsan semper, est augue faucibus neque, vel lacinia nisi diam vel eros. Cras eget mattis arcu, at bibendum dui. Etiam eros augue, tincidunt vitae pharetra in, mattis ut ante. Cras a volutpat nulla, in sodales turpis. Sed suscipit sollicitudin eros, feugiat gravida odio posuere nec. Ut ut ligula velit. Nam a nisi accumsan, varius justo vitae, placerat dui. Proin in congue nisl. Suspendisse ut tincidunt quam. Sed id erat nulla. Nam iaculis ac augue eu volutpat.

  In sit amet velit ultricies, hendrerit nunc id, egestas mauris. Maecenas nec luctus nisi. Proin sed felis gravida, imperdiet urna et, ornare odio. Nullam tempor, ex eu congue convallis, sapien ligula tincidunt felis, et placerat ante justo at nibh. Etiam a lacus sed augue aliquet consequat. Nulla at vulputate tortor. Nunc a mauris tortor. Nam elementum consectetur feugiat. Sed condimentum lorem nec sem dapibus rhoncus. Ut arcu urna, iaculis sed porta ac, fringilla volutpat eros. Mauris ac malesuada est. Duis sollicitudin dolor a rhoncus rutrum.

  Phasellus risus orci, interdum vitae pretium et, porttitor nec mauris. Curabitur viverra dui nibh, tincidunt sollicitudin tellus rutrum in. Vivamus faucibus aliquet neque, ut pulvinar neque lobortis sit amet. Cras fermentum, sem vel tempor efficitur, dolor sem venenatis enim, nec vehicula lacus dolor ut nisl. Aliquam sapien nulla, venenatis ut neque in, sagittis feugiat orci. Vivamus molestie massa id lobortis aliquet. Praesent mattis ex nec dolor consectetur, a gravida nunc pulvinar. Aenean vitae pharetra mauris.

  Nunc laoreet euismod aliquam. Phasellus ut nisl at velit euismod fringilla. Aenean vel neque ante. Aliquam erat volutpat. Praesent varius quam ac ornare pellentesque. Quisque ornare, justo sit amet tristique ultrices, leo felis vulputate nisi, et bibendum erat augue sed tortor. Cras euismod ac leo vel tincidunt. Morbi sollicitudin tristique imperdiet.

  Maecenas sollicitudin luctus quam id dapibus. Donec bibendum nulla id convallis iaculis. Fusce nisl eros, ultrices nec facilisis in, mollis nec turpis. Sed dui felis, eleifend a sem a, lobortis pellentesque eros. Mauris id diam hendrerit turpis consequat lobortis. Duis blandit libero nec erat lobortis tincidunt. Nunc ultrices dolor ut elementum faucibus. Donec rhoncus, est ut malesuada congue, lectus neque convallis leo, sit amet vehicula arcu orci sed nunc. Cras dictum velit nisl, vel interdum mauris pharetra at. Sed id hendrerit ex. Ut consequat sed lectus a interdum. Sed rutrum semper libero, sit amet luctus massa molestie et.

  Fusce fermentum eros non elit efficitur, vitae pretium augue fermentum. Nunc facilisis ligula sem, a hendrerit odio condimentum vel. Donec at odio sed tortor luctus euismod. Quisque fermentum ut leo in viverra. Morbi mattis quam sit amet arcu consectetur vulputate. Sed ac purus elit. Nunc dictum libero non congue consectetur. Aliquam fringilla bibendum neque ac convallis. Ut imperdiet dignissim nulla, sagittis eleifend nibh auctor sed. Curabitur quis tortor sed dolor dignissim vulputate. Nunc eu lectus eu dui suscipit lacinia. Aliquam volutpat justo dictum pellentesque consequat. Aliquam id enim at lacus efficitur euismod a sit amet massa. Aenean dapibus nibh semper mauris viverra lacinia.

  Morbi mattis est ac ligula consectetur, nec porttitor quam venenatis. Nullam sollicitudin orci a eros porta finibus. In sodales ipsum eu quam ornare, sit amet gravida neque auctor. Etiam consequat justo pellentesque ligula malesuada, et rhoncus leo euismod. Morbi sit amet dapibus ante. Duis luctus, arcu at blandit tristique, nunc lectus imperdiet nisl, nec dapibus nisl urna sit amet lorem. Vivamus pharetra sollicitudin pulvinar. In vitae odio mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In sem magna, auctor ut ullamcorper sed, elementum quis lacus. Duis commodo turpis sit amet felis commodo dapibus. Ut fermentum dui et congue hendrerit. Vivamus felis turpis, ultrices at interdum ut, mollis non ex.

</div>);

export default function Home() {
  const t = useTranslations("Main");
  return (
    <main>
      {biolerplate}
      <Schedule />
    </main>
  )
}
